Updating dependancies
ryan-roemer/backbone-testing pull request #26
Opened 2017-01-11 21:05 UTC by cabbiepete

This is still useful as reference so I updated the dependancies and node versions to test against so its a better reference.

2017-01-11 22:18 UTC, ryan-roemer commented
@cabbiepete -- Thanks for chipping in! Can you apply this CI update diff to your PR and see if that fixes what's ailing Travis / Sauce Labs?

https://github.com/ryan-roemer/backbone-testing/compare/chore-updateTravis.diff

2017-01-12 00:54 UTC, cabbiepete commented
@ryan-roemer Travis complaining with "No binary for Chrome browser on your platform" for sauce runner tests. Any ideas?

2017-01-12 04:57 UTC, ryan-roemer requested changes
Have some travis fixes that may help...

2017-01-12 04:57 UTC, ryan-roemer commented on .travis.yml
> -    - BB_TESTING_KARMA=bs
L17-L19 need to be reverted. Only L20 (`BB_TESTING_KARMA=bs`) is replaced with new L20-L22.

2019-09-26 00:17 UTC, closed without merging